services:
  db:
    image: postgres:16-alpine
    container_name: smart-list-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartlist
    ports:
      - '5432:5432'
    volumes:
      - smart-list-data:/var/lib/postgresql/data

volumes:
  smart-list-data:
